Search from db by dish name
NIkitaShykin/OceanBarFrontend pull request #30
Opened 2021-10-30 14:58 UTC by AnnaGromova-FD

By typing search request in the search field, autocomplete options appear;

Autocomplete options appear with delay (debounce);

The input field is cleared, autocomplete prompts are hidden when clicked outside

By clicking on the selected link from autocomplete search, the User is redirected to the appropriate page;

PS: loading animation in the process (separate task)

2021-11-01 11:08 UTC, luchinayan approved these changes

2021-11-01 15:17 UTC, IvanZharnov requested changes
Спасибо за фиксы ошибок линтера 👍

У меня нет доступа к вашему бэку, поэтому было бы хорошо, если бы ты прикрепила скриншоты или видео, как у тебя все работает)

Также написал комменты к коду, если будут вопросы, спрашивай

2021-11-01 15:17 UTC, IvanZharnov commented on src/components/homePageComponents/Navbar/navBarComp.tsx
> +        expand='xxl' fixed='top' className='navbar-fixed'>
Если все атрибуты не помещаются в одну строку, то все нужно переносить:

```
<Navbar
  bg='dark'
  variant='dark'
  expand='xxl'
  fixed='top'
  className='navbar-fixed'
>
```

Поправить все тэги в этом файле

2021-11-01 15:17 UTC, IvanZharnov commented on src/components/homePageComponents/Navbar/navBarComp.tsx
>      <div>
Зачем нужна это обертка `<div>` ?

2021-11-01 15:17 UTC, IvanZharnov commented on src/components/signUpPageComponents/SignUpForm.tsx
> +      {isLoading ? <Spinner/> : null}
` {isLoading && <Spinner/>}`

2021-11-01 15:17 UTC, IvanZharnov commented on src/utils/useDebounce.tsx
> +function useDebounce(value: string, delay: number) {
Вроде как договаривались без `function`

`const useDebounce = (value: string, delay: number) =>  {`

2021-11-01 17:08 UTC, AnnaGromova-FD commented on src/components/homePageComponents/Navbar/Search/Search.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false)
Логика понятна. Единственное тут не получится использовать хук дэбаунс раньше объявления searchQuery.
Все остальные правки учла и перенесла в код. Надеюсь, ничего не пропустила)

2021-11-01 17:28 UTC, AnnaGromova-FD commented
> Спасибо за фиксы ошибок линтера 👍
> 
> У меня нет доступа к вашему бэку, поэтому было бы хорошо, если бы ты прикрепила скриншоты или видео, как у тебя все работает)
> 
> Также написал комменты к коду, если будут вопросы, спрашивай

Наш бэк час назал переехал на AWS, поэтому в SearchBar быстренько поменяла ссылку и теперь тебе будет самому видно как работает поиск. Найденные блюда из автокомплита кликабельны и ведут на соответствующее блюдо, но пока это видно только в консоли (там консоль.лог выведен), а работающая ссылка ведет на категорию. Жду пока Андрей отрендерит меню на страницу с бэка, вместо фейковых данных и сделаю правильную ссылку.
PS: вместе с новым урлом прилетело несколько неопознанных картинок jpg и вызвали ошибки в консоли. Пока никто не понимает что это. Картинки блюд выгледят иначе

2021-11-01 18:22 UTC, IvanZharnov requested changes
Еще пару маленьких моментов

2021-11-01 18:22 UTC, IvanZharnov commented on src/components/homePageComponents/Navbar/Search/Search.tsx
Что бы это было чуть понятнее, можно написать так:

```
type ResponseType = {
  data: {
    data: {
      dishes: Array<Dish>
    }
  }
}
```

2021-11-01 18:22 UTC, IvanZharnov commented on src/components/homePageComponents/Navbar/Search/Search.tsx
> +      )
Этот коммент `// eslint-disable-next-line max-len` нужен только когда у тебя одна длинная строка которую нельзя разбить: `" ... ... ..."`

В твоем случае можно написать так:

```
const filteredDishes = dishes.filter((dish: Dish) => (
  dish.name.toLowerCase().includes(searchQuery.toLowerCase())
))
```

Тоже самое и тут:

```
const response: ResponseType = await axios.get(
  `${url}/menu/?name=${searchQuery}`
)
```

2021-11-01 18:22 UTC, IvanZharnov commented on src/components/homePageComponents/Navbar/Search/Search.tsx
> +          </ul>)
")" должна быть на строку ниже

суть в том, что у тебя две открываются в одной строке "{...(" и закрываться должны тоже в одной ")}"

2021-11-01 22:48 UTC, AMmetro approved these changes
Все конфликтующие файлы файлы в которых не работала при мерже пропускай

2021-11-02 07:14 UTC, IvanZharnov approved these changes
👍

2021-11-02 07:20 UTC, merged