Order details
NIkitaShykin/OceanBarFrontend pull request #59
Opened 2021-11-19 21:18 UTC by AnnaGromova-FD

Summary:
Order details form allows users to check information about the order before order confirmation
Description:
As a user I want order details form so that I can verify information about the order before confirmation
Realisation:
The user places a dish in the cart, fills out an order form specifying the type of order (table reservation, delivery, takeaway). Then the order data are displayed on the order confirmation page for verification. When the "confirm order" button is pressed, the order data are sent to the server (a separate task). When clicking on the cancel button, the user returns to the cart page, the data about the dishes are saved, the data about the order type are not saved

2021-11-22 18:24 UTC, IvanZharnov reviewed
Несколько моментов:

 1. Я выбрал "Наличными", но по итогу пишет, что я плачу онлайн
 2. Может подскроливать страницу на самый верх, чтобы полностью видеть весь заказ?


https://user-images.githubusercontent.com/35364175/142915142-f37df3a2-a527-4bf3-b9c7-dcc646b93176.mov

2021-11-22 19:21 UTC, IvanZharnov requested changes

2021-11-22 19:21 UTC, IvanZharnov commented on src/components/confirmationComponents/DetailsData.tsx
> +      {orderDetails.orderType === 'Навынос' && null}
А зачем вообще эта строка? Она ничего не отображает в любом случае

2021-11-22 19:21 UTC, IvanZharnov commented on src/components/confirmationComponents/OrderDetailsSection.tsx
> +              detail-header-name'>
Почему закрытие тега не на одном уровне с открытием тега?

2021-11-22 19:21 UTC, IvanZharnov commented on src/components/confirmationComponents/OrderDetailsSection.tsx
> +          <div className='details-devider'></div>
Лучше написать самозакрывающийся тег: 
```suggestion
          <div className='details-devider' />
```

2021-11-22 19:21 UTC, IvanZharnov commented on src/components/userProfile/personalData/completedPersonal.tsx
> +        {/* <Col sm={7}></Col> */}
Этот код нужен?

2021-11-22 19:21 UTC, IvanZharnov commented on src/pages/profilePage/profile.tsx
>  // import {DeliveryAdressType} from '../../common/types/userTypes'
Эти комменты зачем?

2021-11-22 19:21 UTC, IvanZharnov commented on src/pages/menuPage/menuPage.tsx
Ненужная строка

2021-11-22 19:21 UTC, IvanZharnov commented on src/components/scrollToTop/ScrollToTopOnMount.tsx
> +const ScrollToTopOnMount = () => {
В чем нужность этого файла. Почему нам не подходит `ScrollToTop`?
В случае если нам действительно нужны 2 разных поведения, мы можем просто пропсами прокидывать `behaviour` и `dependency`  в `ScrollToTop`

2021-11-22 19:21 UTC, IvanZharnov commented on src/components/scrollToTop/ScrollToTop.tsx
> +    behavior: 'smooth'
Интересно, как это должно работать? В документации вроде немного иначе: 
```suggestion
    window.scrollTo({
      top: 0,
      left: 0,
      behavior: 'smooth'
    });
```

2021-11-22 20:55 UTC, AnnaGromova-FD commented on src/common/types/cartTypes.ts
> +export type IOrderType = {
просто для отличия от переменной. Не знаю как правильно. Исправила на OrderItem

>

2021-11-22 20:55 UTC, AnnaGromova-FD commented on src/common/types/userTypes.ts
> +    passwordError?: boolean
почему-то в файлах с расширением ts линт не срабатывает как надо. подправила

2021-11-22 20:56 UTC, AnnaGromova-FD commented on src/components/cartPageComponents/OrderForms/DeliveryForm.tsx
> +
подняла строку

2021-11-22 20:56 UTC, AnnaGromova-FD commented on src/components/cartPageComponents/OrderForms/DeliveryForm.tsx
> +    const [date, setDate] = useState<Date>(new Date('2015-04-02'))
да, это лишнее. Была ошибка с отображением даты заказа, эта строчка осталась после экспериментов. Убрала

2021-11-22 20:56 UTC, AnnaGromova-FD commented on src/components/cartPageComponents/OrderForms/DeliveryForm.tsx
> +      useState<boolean>(false)
теперь вмещаются)

2021-11-22 20:56 UTC, AnnaGromova-FD commented on src/components/userProfile/personalData/completedPersonal.tsx
> +        {/* <Col sm={7}></Col> */}
всё, что касается профайла - не мои компоненты. мне вообще не стоило туда лезть. Для них есть существенные изменения в ветке Андрея

2021-11-22 20:56 UTC, AnnaGromova-FD commented on src/pages/menuPage/menuPage.tsx
подняла строку

2021-11-22 20:56 UTC, AnnaGromova-FD commented on src/components/scrollToTop/ScrollToTopOnMount.tsx
> +const ScrollToTopOnMount = () => {
onMount удалила. Нашла ошибку в том как были прописаны линки в навбаре. Из-за них sсrollToTop не срабатывал, а ScrollToTopOnMount работал. Больше он не нужен

2021-11-22 20:56 UTC, AnnaGromova-FD commented on src/components/scrollToTop/ScrollToTop.tsx
> +    behavior: 'smooth'
да, так гораздо лучше)

2021-11-22 21:01 UTC, IvanZharnov commented on src/common/types/cartTypes.ts
> +export type IOrderType = {
Как я вижу, тип `TOrderItem` у тебя объявлен выше. Будет глупо если будет `TOrderItem` и `OrderItem`. 
Лучше уже назвать `TOrderType` чтобы было хотя бы в одном файле однотипно.

2021-11-22 21:07 UTC, IvanZharnov commented on src/components/userProfile/personalData/completedPersonal.tsx
> +        {/* <Col sm={7}></Col> */}
Для меня не важно где чьи компоненты. Я смотрю твой ПР и пишу комментарии к коду, который тут изменен. Если эти изменения не нужны для твоей задачи, тогда просто удали их.

2021-11-22 21:12 UTC, IvanZharnov commented on src/pages/menuPage/menuPage.tsx
> +  </>
Не нужна обертка `<>...</>`: можно сразу возвращать компоненту

2021-11-22 21:22 UTC, AnnaGromova-FD commented on src/components/cartPageComponents/OrderForms/DeliveryForm.tsx
> +    const home = useInput()
да, это для валидации. Adress для поля с улицей, home для номера дома, time- для тайм слотов. Более точные названия переменных пошли на useState. Или что имеется ввиду?

2021-11-22 21:27 UTC, AnnaGromova-FD commented on src/components/cartPageComponents/OrderForms/DeliveryForm.tsx
>                    aria-label='Floating label select example'
Select time slot подойдет на замену?

2021-11-22 21:30 UTC, AnnaGromova-FD commented on src/components/cartPageComponents/OrderForms/DeliveryForm.tsx
> +                    <span className='street-lable'>г.Минск</span>
ты ушел очень глубоко в коммиты - этот участок сейчас полностью переписан через обращение к апишке и выглядит не так

2021-11-22 21:32 UTC, IvanZharnov commented on src/components/cartPageComponents/OrderForms/DeliveryForm.tsx
> +    const home = useInput()
Ну, когда переменная названа `address` там должна быть информация об адресе.
Если это переменные для валидации я бы назвал что-то из серии `addressValidation`

2021-11-22 21:35 UTC, AnnaGromova-FD commented on src/components/confirmationComponents/DetailsData.tsx
> +      {orderDetails.orderType === 'Навынос' && null}
по ТЗ у меня пустая строка на третий тип доставки, вот и написала. Сейчас вижу, что это излишне. Убираю

2021-11-22 21:40 UTC, AnnaGromova-FD commented on src/components/confirmationComponents/OrderDetailsSection.tsx
> +              detail-header-name'>
исправляю

2021-11-22 21:43 UTC, AnnaGromova-FD commented on src/components/confirmationComponents/OrderDetailsSection.tsx
> +          <div className='details-devider'></div>
что-то новенькое для меня. Раньше не встречала самозакрывающиеся дивы, думала это синтаксис только для кнопок и инпутов

2021-11-22 21:44 UTC, AnnaGromova-FD commented on src/pages/profilePage/profile.tsx
>  // import {DeliveryAdressType} from '../../common/types/userTypes'
убрала

2021-11-22 21:51 UTC, IvanZharnov commented on src/components/cartPageComponents/OrderForms/DeliveryForm.tsx
> +                    <span className='street-lable'>г.Минск</span>
Я пишу комментарии к изменениям в твоем ПР. 
В этом файле 2 раза используется строка `г.Минск`. Я предлагаю её вынести в переменную и в этих местах использовать переменную.

2021-11-23 07:26 UTC, AnnaGromova-FD commented on src/components/cartPageComponents/OrderForms/DeliveryForm.tsx
> +    const home = useInput()
ок, подправлю для ясности

2021-11-23 07:37 UTC, AnnaGromova-FD commented on src/components/cartPageComponents/OrderForms/DeliveryForm.tsx
> +                    <span className='street-lable'>г.Минск</span>
добавила const city ='г.Минск'

2021-11-23 07:42 UTC, IvanZharnov approved these changes

2021-11-23 07:57 UTC, merged